# Taken from TFA Base

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Update APT repos
        run: sudo apt-get update -qy
        
      - name: Install unzip
        run: sudo apt-get install -y unzip
        
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 2.7.18

      - name: Install hererocks
        run: pip install hererocks
        
      - name: Install luajit/luarocks
        run: hererocks $HOME/env --luajit 2.0.4 --luarocks latest
          
      - name: Load source
        run: source $HOME/env/bin/activate  

      - name: Clone gluacheck
        run: git clone https://github.com/impulsh/gluacheck $HOME/gluacheck

  gluacheck:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:        
      - name: Make luarocks
        run: |
          cd $HOME/gluacheck
          luarocks make
          
      - name: Lint
        run: |
          cd $GITHUB_WORKSPACE
          luacheck .
